(import date)
(import ../slog)
(import json)

(slog/info "loool")
(def info slog/info)
(def stream stdout)
(def logger (slog/new stream json/encode))
(slog/set-default logger)
(slog/info "loool")
(slog/set-level :debug)
(info "hello" :count 3 :a 1 :b 2 :c (:strftime (:gmtime (date/time)) :iso8601))
(slog/debug "Debug error" :a 1 :b 2)
# (prin stream)
